environment:
  sdk: '^3.2.0'
name: "gay"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"
dependencies:
  webview_flutter: ^4.4.4
  flutter_inappwebview: ^5.7.0
  url_launcher:
  flutter_local_notifications: ^9.2.0
  flutter_launcher_icons: "^0.13.1"

